POST http://localhost:3000/api/users
Content-Type: application/json

{
"firstName": "Edem",
"lastName": "Quashigah",
"email": "edemq123@gmail.com",
"password": "password"
}

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
"firstName": "Edem",
"lastName": "Doe",
"email": "example2@mail.com",
"password": "hashedpassword"
}

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
"firstName": "Fafa",
"lastName": "Doe",
"email": "fafa@mail.com",
"password": "hashedpassword"
}